//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckoutService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingRule
    {
        public string CustomerID { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> FixedQuantity { get; set; }
        public Nullable<int> MinimumQuantity { get; set; }
        public Nullable<int> DiscountedPriceByQuantity { get; set; }
        public Nullable<decimal> DiscountedPricePerProduct { get; set; }
    }
}
